language: node_js
node_js:
  - "lts/*"

branches:
  only:
    - site

cache: yarn

script:
  - yarn build
  - cp static/logo.png dist/logo.png
  - cp static/robots.txt dist/robots.txt

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: dist
  on:
    branch: site
