language: node_js
node_js:
  - "lts/*"

branches:
  only:
    - gh-pages

cache: yarn

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: dist
  on:
    branch: gh-pages
